### ISSUE TITLE
CORS issues? (Onebox generation and Image fetching broken)

### ISSUE THREAD

**Issue by aschrijver** [YunoHost-Apps/discourse_ynh#108]
### Describe the bug

I recently did a fresh Discourse install on Yunohost for the forum https://discuss.coding.social and everything worked fine. When dropping a link in a post the Onebox functionality would kick in and generate a nice link preview from the opengraph data found at the URL.

That all suddenly stopped working. Dropping a link no longer generates the preview, just shows the link text.

This while since initial install I did not do any updates / upgrades of both Yunohost itself or any of the applications I have installed, nor did I tweak anything in the admin interface of Discourse, or even updated the VPS itself. Everything is box-standard Yunohost + Discourse.

### Context

- Hardware: VPS bought online
- YunoHost version: 4.3.6.2 (stable)
- I have access to my server: Through SSH as well as through the webadmin
- Are you in a special context or did you perform some particular tweaking on your YunoHost instance?: No
- Using, or trying to install package version/branch: 2.7.13~ynh1

### Steps to reproduce

Any URL typed into a discourse post on a single line that would normally trigger onebox generation, just displays the text. The hourglass icon for the generator appears _very_ briefly, then stops. There's no fetching of remote opengraph metadata.

![Screenshot from 2022-04-04 10-33-10](https://user-images.githubusercontent.com/5111931/161505652-5ab66ba1-de9a-435f-afa4-dd32c2d4d746.png)

### Expected behavior

Dropping a link should yield a onebox similar to the following:

![Screenshot from 2022-04-04 10-35-04](https://user-images.githubusercontent.com/5111931/161505934-d41d3718-1426-49d0-95d0-32d9aeed6f6a.png)

### Logs

There are no relevant logs that relate to this issue, neither on Yunohost nor in the admin UI of Discourse. In Yunohost the last log entries date back to when oneboxes were still operational.

The reason I report this issue in this repository is that I operate various Discourse forums that are not hosted on Yunohost, where this never has been a problem. Whereas I know of one other Yunohost + Discourse that has the exact same issue, and it also happened unexpectedly (at the time they blamed themself for trying to install a Discourse plugin, but now it looks like that wasn't the cause)

This forum is https://fediverse.town operated by @paulatothepeople and I create a topic to notify them at: https://fediverse.town/t/inability-to-generate-link-previews-serious-bug/404

I don't know if I can troubleshoot a yuno-hosted Discourse in the same way as a regular installation (via the discourse docker install). Looks like it is needed to dive into SSH and find more information there as to what's causing this.

As a general feedback to the Yunohost project and the Discourse package in particular: It is a pity that the Discourse upgrade facilities cannot be used, as I find them to be pretty solid and stable. In Yunohost I feel that too much information is hidden from me, for the sake of facilitating ease-of-use. This is fine if everything works, but leaves on in the dark when trouble occurs. Maybe the README can be updated with a section on 'Troubleshooting', just enough instruction on where yunohost ends, and discourse sysadmin takes over.

**Comment by aschrijver** [comment]
![Screenshot from 2022-04-06 10-42-40](https://user-images.githubusercontent.com/5111931/161934161-7cf661b3-55d2-46c8-a987-c343d636f3bc.png)

First link is to: https://ec.europa.eu/info/law/better-regulation/have-your-say/initiatives/13394-Brain-drain-mitigating-challenges-associated-with-population-decline-communication-_en

**Comment by tituspijean** [comment]
I might suspect CORS settings, but we will need extracts from your browser console to confirm it.

**Comment by aschrijver** [comment]
Ah, it is good you mention. I thought there were no logs, but an 'Inspect' in Firefox gives errors relating to Onebox while typing `https://fediverse.codeberg.page` in a new topic. A site that has a whole bunch of opengraph and SEO metadata and should generate a preview.

First a warning message:

```
Content Security Policy: This site (https://discuss.coding.social) has a Report-Only policy without a report URI. CSP will not block and cannot report violations of this policy.
```

Followed by a 404 error:

```
XHRGET https://discuss.coding.social/onebox?url=https://fediverse.codeberg.page/&refresh=false&category_id=5&topic_id=45
[HTTP/1.1 404 Not Found 0ms]

GET https://discuss.coding.social/onebox?url=https://fediverse.codeberg.page/&refresh=false&category_id=5&topic_id=45
Status: 404 Not Found
Version: HTTP/1.1
Transferred: 0 B (0 B size)
Referrer: Policyno-referrer-when-downgrade
content-length: 0
content-security-policy: upgrade-insecure-requests
content-security-policy-report-only: default-src https: data: blob: ; object-src https: data: 'unsafe-inline'; style-src https: data: 'unsafe-inline' ; script-src https: data: 'unsafe-inline' 'unsafe-eval'
content-type: text/plain; charset=utf-8
date: Sun, 17 Apr 2022 09:43:01 GMT
permissions-policy: interest-cohort=()
referrer-policy: no-referrer-when-downgrade
server: nginx
strict-transport-security: max-age=63072000; includeSubDomains; preload
vary: Accept
x-content-type-options: nosniff
x-discourse-route: onebox/show
x-discourse-username: myusername
x-download-options: noopen
X-Firefox-Spdy: h2
x-frame-options: SAMEORIGIN
x-permitted-cross-domain-policies: none
x-runtime: 0.072555
x-sso-wat: You've just been SSOed
x-xss-protection: 1; mode=block
Accept: text/html, */*; q=0.01
Accept-Encoding: gzip, deflate, br
Accept-Language: en-US,en;q=0.5
Connection: keep-alive
Cookie:_t=[redacted]; _forum_session=[redacted]; _bypass_cache=true
Discourse-Logged-In: true
Discourse-Present: true
DNT: 1
Host: discuss.coding.social
Referer: https://discuss.coding.social/t/question-does-having-a-technology-vision-help-adoption/45/4
Sec-Fetch-Dest: empty
Sec-Fetch-Mode: cors
Sec-Fetch-Site: same-origin
Sec-GPC: 1
User-Agent: Mozilla/5.0 (X11; Ubuntu; Linux x86_64; [redacted]
X-CSRF-Token: [redacted]
X-Requested-With: XMLHttpRequest
```

**Comment by aschrijver** [comment]
I just found another issue, and like @tituspijean says it looks like there's CORS problem as the cause.

When you add an image in Markdown and use an external image URL in doing so, then at the time that Discourse will fetch the remote image to store in its own archive locally, a similar error occurs and the image is broken, is no longer displayed.

The warnings in the console is the following:

```
Content Security Policy: This site (https://discuss.coding.social) has a Report-Only policy without a report URI. CSP will not block and cannot report violations of this policy. 28

Referrer Policy: Less restricted policies, including ‘no-referrer-when-downgrade’, ‘origin-when-cross-origin’ and ‘unsafe-url’, will be ignored soon for the cross-site request: https://socialhub.activitypub.rocks/uploads/default/original/1X/71be05cf3c42e4ae015eb5cdb9f7f956faf8a684.png
```

There's no error in the log, but the image isn't fetched.

**Comment by zamentur** [comment]
Note that infobox features could include external trackers compromizing private messages title through referer for example.

**Comment by aschrijver** [comment]
Somehow:

https://fosstodon.org

Generates a OneBox, but:

https://mastodon.technology

Does not.

They are both running the same version of Mastodon (v3.5.3). I tested this on 2 yunohosted Discourse forums.

**Comment by aschrijver** [comment]
The latest upgrade to 2.8.8 fixed this issue.
