### ISSUE TITLE
Upgrade to 2.8.6~ynh1 fails

### ISSUE THREAD

**Issue by cloo** [YunoHost-Apps/discourse_ynh#123]
Upgrading procedure fails.
![220804-225752](https://user-images.githubusercontent.com/651760/182941427-4b9a40d6-6a66-43dd-b594-8328bb458086.png)

### Context

- Hardware: *Old laptop or computer*
- YunoHost version: 4.3.6.3
- I have access to my server: *Through SSH*
- Are you in a special context or did you perform some particular tweaking on your YunoHost instance?: *no*
- Using, or trying to install package version/branch:  *2.8.6~ynh1*
- If upgrading, current package version: *2.7.13~ynh2*
 
### Logs
 
https://paste.yunohost.org/raw/ubeyomusot

**Comment by aschrijver** [comment]
I tried the upgrade as well (hoping it would solve #108 ) and the upgrade failed, but a bit further in the process than where @cloo ended up.

![Screenshot from 2022-08-09 09-55-41](https://user-images.githubusercontent.com/5111931/183596895-f64978e4-735c-42d1-8b71-02ac250077b8.png)

(The `getwcd() failed` repeats many times, until msgs "the app was restored to the way it was before the failed upgrade". For anyone that tries to upgrade to, a reassurance: my forum is still working like before :smiling_face_with_tear: )

### Context

- Hardware: _Old laptop or computer_
- YunoHost version: 4.3.6.3
- I have access to my server: _Through SSH_
- Are you in a special context or did you perform some particular tweaking on your YunoHost instance?: _no_
- Using, or trying to install package version/branch: _2.8.6~ynh1_
- If upgrading, current package version: _2.7.13~ynh2_

### Logs

https://paste.yunohost.org/raw/rikayumaco
