### ISSUE TITLE
Upgrade to 2.8.7~ynh1 fails

### ISSUE THREAD

**Issue by aschrijver** [YunoHost-Apps/discourse_ynh#127]
I tried the upgrade (hoping it would solve #108 ) and it failed to complete, but a bit further in the process than where @cloo ended up in #123 

![Screenshot from 2022-08-09 09-55-41](https://user-images.githubusercontent.com/5111931/183596895-f64978e4-735c-42d1-8b71-02ac250077b8.png)

(The `getwcd() failed` repeats many times, until msgs "the app was restored to the way it was before the failed upgrade". For anyone that tries to upgrade to, a reassurance: my forum is still working like before :smiling_face_with_tear: )

### Context

- Hardware: _Old laptop or computer_
- YunoHost version: 4.3.6.3
- I have access to my server: _Through SSH_
- Are you in a special context or did you perform some particular tweaking on your YunoHost instance?: _no_
- Using, or trying to install package version/branch: _2.8.7~ynh1_
- If upgrading, current package version: _2.7.13~ynh2_

### Logs

https://paste.yunohost.org/raw/rikayumaco

**Comment by cloo** [comment]
Upgrade to 2.8.8 finally worked.

**Comment by aschrijver** [comment]
Thank you, and thanks to the maintainers! I can confirm that. I first upgraded Yunohost to 4.4.2.1 and then did the Discourse upgrade, which succeeded flawlessly. And.. hurray :tada: with that #108 is fixed as well :smiley:
