### ISSUE TITLE
Unknown version

### ISSUE THREAD

**Issue by Josue-T** [YunoHost-Apps/discourse_ynh#13]
Hello,

When I go on the admin panel discourse show me unknown version and it show that I'm up to date but in the reality I'm not up to date.

Look like the same issue than here : https://meta.discourse.org/t/some-users-getting-unknown-error-upon-login/85905

Anybody else have this issue ?

**Comment by JimboJoe** [comment]
I have the same problem, and I think it is due to the fact that we don't use the official install way (which is based on Docker, and especially on a git clone).
