### ISSUE TITLE
Update to 2.8.14~ynh2 ynh4 ynh5 failed - service does not start

### ISSUE THREAD

**Issue by tio-trom** [YunoHost-Apps/discourse_ynh#178]
- Hardware: *VPS bought online*
- YunoHost version: 11.2.10.3
- I have access to my server: *Through SSH | through the webadmin | direct access via keyboard / screen | ...*
- Are you in a special context or did you perform some particular tweaking on your YunoHost instance?: *no*

The logs from the failed service - https://paste.yunohost.org/edojadecim

```
Mar 21 01:11:39 bundle[2054769]: Activating bundler (~> 2.3) failed:
Mar 21 01:11:39 bundle[2054769]: Could not find 'bundler' (2.3.22) required by your /var/www/discourse/Gemfile.lock.
Mar 21 01:11:39 bundle[2054769]: To update to the latest version installed on your system, run `bundle update --bundler`.
Mar 21 01:11:39 bundle[2054769]: To install the missing version, run `gem install bundler:2.3.22`
Mar 21 01:11:39 bundle[2054769]: Checked in 'GEM_PATH=/var/www/discourse/.gem/ruby/3.0.0:/opt/rbenv/versions/3.0.0/lib/ruby/gems/3.0.0' , execute `gem env` for more information
Mar 21 01:11:39 bundle[2054769]: To install the version of bundler this project requires, run `gem install bundler -v '~> 2.3'`
Mar 21 01:11:39 systemd[1]: discourse.service: Main process exited, code=exited, status=42/n/a
Mar 21 01:11:39 systemd[1]: discourse.service: Failed with result 'exit-code'.
```

**Comment by tio-trom** [comment]
Backup restore also fails in the same way - https://server.tromsite.com/yunohost/admin/#/tools/logs/20240320-232320-backup_restore_app-discourse

**Comment by aschrijver** [comment]
Same situation for me, also 11.2.10.3 

Update 2.8.14~ynh1 --> 2.8.14~ynh2 seemed successful. But no forum access:

> 502 Bad Gateway
> 
> If you see this page, your connection with the server is working but the internal service providing this path is not responding.
> 
> Administrator, make sure that the service is running, and check its logs if it is not. The Services page is in your webadmin, under Tools > Services.
> 
> Thank you for using YunoHost.

The tools > services also doesn't load:

![Screenshot from 2024-03-30 09-00-28](https://github.com/YunoHost-Apps/discourse_ynh/assets/5111931/54540525-9fca-4adf-88c7-366a895fa906)

Discourse service is marked "auto-restart" in services list. Fails.

![Screenshot from 2024-03-30 09-05-09](https://github.com/YunoHost-Apps/discourse_ynh/assets/5111931/0c6e6002-399d-49f5-b0c1-230970f85f40)

Restore via the UI fails (Pressing 'Restore' button and confirming, simply does nothing).

Via SSH access the advised commands `sudo yunohost service restart discourse` says "successful restart" (but no access), and `sudo yunohost service log discourse` only reports "Killed" (not logging anything).

**Comment by aschrijver** [comment]
My only solution to fix the issue was to restore the VPS backup via my hosting providers' tools.

**Comment by squattertim** [comment]
Have You tried to install missing bundler version? It worked for me, but after that we are facing LDAP problem described here - https://github.com/YunoHost-Apps/discourse_ynh/issues/179

**Comment by Salamandar** [comment]
I can't reproduce :( Could you guys please share the update logs via the webadmin ?

**Comment by tio-trom** [comment]
I have restored my Discourse so I cannot provide any logs. I find it impossible to update Discourse and/or restore for the past many months now. Maybe the rest can help with some logs. I can try to test any newer versions of Discourse...

**Comment by aschrijver** [comment]
Did anyone here try 2.8.14~ynh1 to 2.8.14~ynh4 ?

**Comment by tio-trom** [comment]
> Did anyone here try 2.8.14~ynh1 to 2.8.14~ynh4 ?

I will try it these days and report back.

**Comment by tio-trom** [comment]
Update to the ynh4 also failed https://paste.yunohost.org/raw/upapuzojol - restore also failed. Discord is stuck :D - no updates, no restores possible.

**Comment by tio-trom** [comment]
Update to the ynh5 also fails.... I am baffled what is happening here? :D - Full logs here https://paste.yunohost.org/raw/upapuzojol . Restore also failed - https://paste.yunohost.org/raw/ekiforivoq

**Comment by aschrijver** [comment]
Update the title? Not sure if maintainers are aware we are having these issues still.

**Comment by tituspijean** [comment]
@tio-trom in both your failed upgrade logs, I see that it fails to upgrade the "Material Design Theme".

```log
2024-07-17 04:31:15,947: DEBUG - fatal: not a git repository (or any of the parent directories): .git
2024-07-17 04:31:30,476: DEBUG - Checking 'Material Design Theme' for 'default'... Failed to update 'Material Design Theme': Malformed version number string < 3.3.0.beta1-dev 2024-07-17 04:31:30,480: DEBUG - rake aborted! 2024-07-17 04:31:30,481: DEBUG - ArgumentError: Malformed version number string < 3.3.0.beta1-dev
```
i see two things here:
- "not a git repository": how have you installed the Material Design theme? Was it the "official" method?
- The "malformed version number" is the Discourse version requirement. Could you try removing that theme before upgrade and try again?

**Comment by tio-trom** [comment]
Oh wow finally!!! Thank you @tituspijean !! Removing that theme worked. I have no clue how that theme got installed tho. Full log of the upgrade here if anyone is curious - https://paste.yunohost.org/raw/isupetufoh

This version is still way way behind the latest release tho

![image](https://github.com/user-attachments/assets/5a96c7e6-d6c8-4baf-9e91-d82fe64dfa85)

I wonder what is the issue with this package but well that's another issue...
