### ISSUE TITLE
[Regression 2.8.14~ynh2] Can't login using LDAP

### ISSUE THREAD

**Issue by ziima** [YunoHost-Apps/discourse_ynh#179]
### Describe the bug

After upgrade of discourse to `2.8.14~ynh2`, it's umpossible to login to the discourse using LDAP provider.

### Context

- Hardware: *VPS bought online*
- YunoHost version: 11.2.10.3
- I have access to my server: *Through SSH | through the webadmin*
- Are you in a special context or did you perform some particular tweaking on your YunoHost instance?: *no*
  - If yes, please explain: Not aware of anything relevant
- If upgrading, current package version: 2.8.14~ynh2

### Steps to reproduce

- *If the error occurs in your browser, explain what you did:*
   1. *Go to `https://<yunohost>/auth/ldap`
   2. Enter credentials and submit the form
   3. *See error:* `Sorry, there was an error authorizing your account. Please try again.`
   4. See log `/var/www/discourse/log/production.log`:
```
(ldap) Request phase initiated.
Started POST "/auth/ldap/callback" for 185.158.64.16 at 2024-03-29 13:54:35 +0100
(ldap) Setup endpoint detected, running now.
(ldap) Callback phase initiated.
(ldap) Authentication failure! ldap_error: TypeError, no implicit conversion of Hash into String
Started GET "/auth/failure?message=ldap_error&strategy=ldap" for 185.158.64.16 at 2024-03-29 13:54:35 +0100
```

### Expected behavior

Login passed.

### Logs

No relevant logs under `yunohost log` command.

### References
Also reported at https://forum.yunohost.org/t/discourse-unable-to-login-with-admin/29074

**Comment by ziima** [comment]
I can confirm that Discourse works correctly once downgraded back to `2.8.14~ynh1`. The downgrade itself isn't easy.

Downgrade workflow:
1. Make discourse backup (from the discourse itself, not the Yunohost)
2. Clone this repo
3. Checkout `0522164` which corresponds to `2.8.14~ynh1`.
4. Apply patch needed for install to pass
```diff
diff --git a/scripts/install b/scripts/install
index 9509e6c..aec1f89 100644
--- a/scripts/install
+++ b/scripts/install
@@ -163,7 +163,7 @@ ynh_add_config --template="../conf/secrets.yml" --destination="$final_path/confi
 pushd "$final_path"
        ynh_use_ruby
        # Install bundler, a gems installer
-       ynh_gem install bundler
+       ynh_gem install bundler -v 2.4.22
        # Install without documentation
        ynh_exec_as $app echo "gem: --no-ri --no-rdoc" >> "$final_path/.gemrc"
 popd
```
5. Delete the discourse app
6. Install the discourse app from the cloned and patched repository
7. Restore discourse backup

**Comment by MadMan247** [comment]
I intend to bump this, as it makes the initial setup impossible: 

"Default administrator and YunoHost users must login using LDAP"

Thank you for your efforts!

**Comment by megavillain** [comment]
Just ran into this issue and stumbled into here.

**Comment by treved3** [comment]
Running into the same issue, only difference is this is an install not an upgrade.

**Comment by rodinux** [comment]
> I can confirm that Discourse works correctly once downgraded back to `2.8.14~ynh1`. The downgrade itself isn't easy.
> 
> Downgrade workflow:
> 
>     1. Make discourse backup (from the discourse itself, not the Yunohost)
> 
>     2. Clone this repo
> 
>     3. Checkout `0522164` which corresponds to `2.8.14~ynh1`.
> 
>     4. Apply patch needed for install to pass
> 
> 
> ```diff
> diff --git a/scripts/install b/scripts/install
> index 9509e6c..aec1f89 100644
> --- a/scripts/install
> +++ b/scripts/install
> @@ -163,7 +163,7 @@ ynh_add_config --template="../conf/secrets.yml" --destination="$final_path/confi
>  pushd "$final_path"
>         ynh_use_ruby
>         # Install bundler, a gems installer
> -       ynh_gem install bundler
> +       ynh_gem install bundler -v 2.4.22
>         # Install without documentation
>         ynh_exec_as $app echo "gem: --no-ri --no-rdoc" >> "$final_path/.gemrc"
>  popd
> ```
> 
>     5. Delete the discourse app
> 
>     6. Install the discourse app from the cloned and patched repository
> 
>     7. Restore discourse backup

I have try without upgrading for a new install 
* do a fork
* create a branch fix and checkout in this fix branch
* git checkout `0522164`
* change the line as you said `ynh_gem install bundler -v 2.4.22`

but the install did not work as excepted... I think is not a really good idea to use old scripts not V2 now in Yunohost...
I hope this package could be repair... 

seems related to #183 and #184 

Is there a way to install this application, create a new user not in LDAP and give him admin rights by cli ??

**Comment by rodinux** [comment]
> Running into the same issue, only difference is this is an install not an upgrade.
> 
> Searching for '(ldap) Authentication failure! ldap_error: TypeError, no implicit conversion of Hash into String' I find an issue that has been resolved in january 2023: [jonmbake/discourse-ldap-auth#71](https://github.com/jonmbake/discourse-ldap-auth/issues/71) and here: https://meta.discourse.org/t/jonmbake-discourse-ldap-auth-ldap-plugin-not-working-after-upgrading-discourse-to-3-0-0-beta16/250979
> 
> Not sure what yunohosts stack is in this regard and if it's the same problem.

It is strange, in the Gemfile, ther no `gem 'net-ldap'` and no `gem 'omniauth-ldap'`
