### ISSUE TITLE
Installation failure

### ISSUE THREAD

**Issue by MadMan247** [YunoHost-Apps/discourse_ynh#184]
man, at least my last attempt installed, even if I couldn't use it due to LDAP.

### Describe the bug
Installation error

### Context
- Hardware: Raspberry Pi at home (4B 4GB)
- YunoHost version: 11.2.12
- I have access to my server: Through SSH | through the webadmin
- Are you in a special context or did you perform some particular tweaking on your YunoHost instance?: no
- Using, or trying to install package version/branch: 2.8.14~ynh3

### Steps to reproduce
-attempted install

### Expected behavior
-Successful installation

did not install, could not install a dependency.

### Logs
https://paste.yunohost.org/raw/xuqoruzagi

**Comment by Salamandar** [comment]
Should be fixed by b2dead.

**Comment by MadMan247** [comment]
Let's bring this back to life
https://paste.yunohost.org/raw/zaqawetezu

**Comment by MadMan247** [comment]
@Salamandar have you seen this?
