### ISSUE TITLE
swap partition requirement ?

### ISSUE THREAD

**Issue by JDmnT** [YunoHost-Apps/discourse_ynh#20]
2019-04-02 02:50:39,360: DEBUG - + echo 'You must have a swap partition in order to install and use this application'

I believe this is should be improve

1. such as swap could be a file such as /swapfile
2. and or might be externally managed by the hypervisor such as vmware and proxmox
3. in a ha situation swap must be avoid to don't loose data suchas docker swarm, ...

So it is a nice test and attention of you to check if I have a swap partition but in my case the lxc host have 24GB of RAM so I tough he didn't need swap 

what do you think ?
or I could bypass this ?

**Comment by JimboJoe** [comment]
Hi,
Items 1 and 2 will be already covered provided you have a swap mount (the swap availability is checked in /proc/meminfo).
As swap is required by Discourse, and your use case (and other provided examples) is very far from YunoHost user base and target, I'd better not support that, and recommend you set a very small swap file (there are/will be other apps with that requirement) :wink:

**Comment by decentral1se** [comment]
> As swap is required by Discourse, and your use case (and other provided examples) is very far from YunoHost user base and target, I'd better not support that, and recommend you set a very small swap file (there are/will be other apps with that requirement)

Sounds good to me!

**Comment by JimboJoe** [comment]
Closing this for now, as the explanation seemed to be sufficient.

**Comment by arthurlogilab** [comment]
@JimboJoe thanks for the explanation, I got hit by this too (`apt install dphys-swapfile` solved it). Do you have a link to the discourse documentation stating the requirement for swap ? Do you have other examples of ynh apps with this requirement ?

**Comment by JimboJoe** [comment]
Hi,
The requirement for the swap is in the [README](https://github.com/discourse/discourse/blob/master/docs/INSTALL.md).
As far as I know, the gitlab ynh application also has requirements regarding swap memory.
