### ISSUE TITLE
Discourse 2.5 upgrade work

### ISSUE THREAD

**Issue by decentral1se** [YunoHost-Apps/discourse_ynh#33]
See:

  * https://meta.discourse.org/t/discourse-version-2-4/108194.
  * https://github.com/discourse/discourse/releases/tag/v2.4.0.beta2

It's not released yet but we can use this issue to track that later on.

**Comment by JimboJoe** [comment]
Discourse 2.4.0 [has been released](https://meta.discourse.org/t/discourse-version-2-4/108194).

From my first tries, there is at least:
* conflict on 3000 TCP port with other apps (e.g. Grafana) --> need to use a proper helper
* need for Redis 4+ which isn't available in Debian Stretch (but in Buster and stretch-backports)

**Comment by JimboJoe** [comment]
See this ongoing PR https://github.com/YunoHost-Apps/discourse_ynh/pull/61
