### ISSUE TITLE
Bug plugin code review

### ISSUE THREAD

**Issue by Murloc6** [YunoHost-Apps/discourse_ynh#42]
First of all, thank you for your work :) we tried it and it works like a charm.

Nevertheless we tried to use the officiel plugin ["code review"](https://github.com/discourse/discourse-code-review) but it didn't work. We have this log message in the javascript console :
```
Error: Could not find module 'discourse/widgets/default-notification-item' imported from 'discourse/plugins/discourse-code-review/discourse/widgets/code-review-commit-approved-notification-item'
```

Does it mean we have to install the default-notification-item plugin before ?

Thank you for your answer

**Comment by JimboJoe** [comment]
Hello,
I haven't played much with Discourse plugins, so I won't be of much help here...
How did you install the plugin?
