### ISSUE TITLE
Unable to install dependencies

### ISSUE THREAD

**Issue by stemy2** [YunoHost-Apps/discourse_ynh#45]
Hello,

This message appeared when i tried unsuccessfully to install the app.

[The full log](https://paste.yunohost.org/raw/uqikakaziz)

There's a side effect too: when i try to install it, it wipes my main mastodon stream, that is installed on the same server.

**Comment by JimboJoe** [comment]
There seem to be interactions with the onlyoffice package:
```
2019-10-12 21:35:13,813: DEBUG - The following packages will be REMOVED:
2019-10-12 21:35:13,814: WARNING - E: Packages need to be removed but remove is disabled.
2019-10-12 21:35:13,815: DEBUG -   libcurl4-nss-dev onlyoffice-ynh-deps
```
Is apt-get/dpkg in a correct state (no pending changes)...?

**Comment by stemy2** [comment]
Not that i know.

**Comment by JimboJoe** [comment]
Looks like libcurl4-openssl-dev and libcurl4-nss-dev (needed by onlyoffice) are conflicting, then...
I'm not sure about the way forward on this... cc @yalh76

**Comment by yalh76** [comment]
me neither ^^
I think the best would be to not install all the yunohost available packages on the same instance...
