### ISSUE TITLE
yunohsot 3.1 no way to install - The user discourse was not found

### ISSUE THREAD

**Issue by gamersalpha** [YunoHost-Apps/discourse_ynh#5]
Hello so on my frech install of yunohsot i want install discourse
but when i install i have this error : 

what do u think please : 

The user discourse was not found
```

/etc/nginx/conf.d/domaine.fr.d/discourse.conf wasn't deleted because it doesn't exist.

Avoid deleting .

sudo: unable to initialize policy plugin

sudo: unknown user: postgres

sudo: unable to initialize policy plugin

sudo: unknown user: postgres

/opt/rbenv wasn't deleted because it doesn't exist.

rm: cannot remove '/etc/profile.d/rbenv.sh': No such file or directory

_common.sh: line 444: /opt/rbenv/bin/rbenv: No such file or directory

grep: /opt/rbenv/ynh_app_version: No such file or directory

sed: can't read /opt/rbenv/ynh_app_version: No such file or directory

E: Unable to locate package discourse-ynh-deps

!!

discourse's script has encountered an error. Its execution was cancelled.

!!

You must have a minimum of 1Gb available memory (RAM+swap) for the installation

Connecté

Non autorisé
```

**Comment by gamersalpha** [comment]
I have this page for one hours, i think that's means install failed no ?

![image](https://user-images.githubusercontent.com/32466950/44627696-5ab3ec80-a932-11e8-9c88-29b9dfc63d19.png)

**Comment by JimboJoe** [comment]
As stated in the README, and specifically in the log you shared: `You must have a minimum of 1Gb available memory (RAM+swap) for the installation`.

**Comment by gamersalpha** [comment]
humm a raspberry have 1go so what is the problém ?

**Comment by gamersalpha** [comment]
et me donner la solution directement ça aurait pas été plus simple ?


http://cl-rpi.fr/index.php/2017/09/25/augmenter-swap-de-raspberry-pi/

**Comment by gamersalpha** [comment]
et me donner la solution directement ça aurait pas été plus simple ?


http://cl-rpi.fr/index.php/2017/09/25/augmenter-swap-de-raspberry-pi/

**Comment by JimboJoe** [comment]
I could certainly not give you THE solution as I don't know your server, hence there could possibly be numerous options, among which enlarging the swap size (which you did), stop unnecessary services, etc.

I detected an unappropriated reaction to my help: please be kind and consider all of this is given and shared to the community on many people's spare time. Otherwise you'll end up with no help at all, and even worse, contributors losing their motivation... :frowning_face:
