### ISSUE TITLE
No ynh_maintenance_mode_OFF after failed upgrade

### ISSUE THREAD

**Issue by spctrlth** [YunoHost-Apps/discourse_ynh#50]
Hey,
One reason why a backup can be restored is because an upgrade failed. We had this and noticed that we still got a maintenance screen after the app was restored.

I see in the upgrade script that `ynh_maintenance_mode_ON` is used (which is very nice btw) and the end of the script has `ynh_maintenance_mode_OFF`.

The problem now is that when the upgrade fails, it will never get to `ynh_maintenance_mode_OFF`. I assume one way to fix it is to add `ynh_maintenance_mode_OFF` to the restore or remove script as well (and probably preferably at the end of the restore script for this case).

**Comment by arthurlogilab** [comment]
Getting the same problem.  (and #51 too)

Would it be usable to have the `ynh_maintenance_mode_OFF` call at the end of the restore script ? 

my workaround was to : 

```
rm /etc/nginx/conf.d/y.intra.logilab.fr.d/maintenance.discourse.conf 
systemct reload nginx
```
