### ISSUE TITLE
Integration level

### ISSUE THREAD

**Issue by Kapu06** [YunoHost-Apps/discourse_ynh#53]
Hello, until recently I could install Discourse without any trouble via Yunohost. But recently the integration level has dropped to 0 and I can't install it on my server. I don't know where the problem comes from :/ 

Would it be possible for you to make it available again for installation via Yunohost?

Thanks for your work!!!

**Comment by JimboJoe** [comment]
Please see #51: current upstream stable version installation fail; we're waiting for a Discourse release fixing that...

**Comment by JimboJoe** [comment]
Fixed by #54 (2.3.10 release)
