### ISSUE TITLE
Unable to install plugin/restart service

### ISSUE THREAD

**Issue by Kapu06** [YunoHost-Apps/discourse_ynh#55]
Hi, and thanks again for your job ! I have an issue with the plugin installation, 
the following command doesn't work:
   ` systemctl restart discourse-puma`
`Failed to restart discourse-puma.service: Unit discourse-puma.service not found.`

The previous lines worked :  
```
sudo -i -u discourse RAILS_ENV=production bin/rake --trace plugin:install repo=https://github.com/discourse/discourse-solved (for example)
sudo -i -u discourse RAILS_ENV=production bin/rake --trace assets:precompile
```

How can I restart the service to finish the installation ?
The plugin doesn't install even if I restart my server?

The plugin is : https://meta.discourse.org/t/chatroom-integration-plugin-discourse-chat-integration/66522
Discourse : 2.3.7

**Comment by Kapu06** [comment]
I upgraded Discourse to 2.3.10 and the plugin doesn't install :/

**Comment by JimboJoe** [comment]
As stated in the package README, the command to restart the service is:
```
systemctl restart discourse
```
(and not discourse-puma)

Furthermore, what do you mean by "the plugin doesn't install"? Do you have error messages?
Did you follow the instructions in the link you shared?

**Comment by Kapu06** [comment]
Ok, sorry, I followed the instructions in the Yunohost forum.
I also followed the instructions there to install the plugin and went to /var/www/discourse, but it works only if you go to /var/www/discourse/plugins.

But the installation failed because ember is not included in the yunohost package of Discourse. In fact the installation worked, but the forum couldn't load (I had a blank page in my browsers) because ember was missing.
Why is this file not included in the package ? [discourse-loader.js](https://github.com/discourse/discourse/blob/25ebfd599840f386c21c6ffc1b7f0d1f9d790f2f/app/assets/javascripts/discourse-loader.js). As I understand, ember is loaded there for the discourse forum.
Many plugins need ember.

**Comment by JimboJoe** [comment]
I've just tried the procedure, and it seems to work (in particular in the ̀/var/www/discourse`), the plugin is listed in the plugins interface.
How did you diagnose the missing ember?

**Comment by Kapu06** [comment]
My bad, it was'nt this  plugin that I tried, but this one : https://meta.discourse.org/t/discourse-calendar/97376 (calendar). But both seem to need ember.

How I came to think about ember. I get a blank page when I try to go to my forum, when I inspect the element with the firefox tool, I get in the debug section : 
```
Error: Could not find module `rsvp` imported from `discourse/plugins/discourse-calendar/initializers/discourse-calendar` _ember_jquery-0ae86c6a7527a99c2b9b8a11521273bd9cb4f7d41bc546df081b7ee94f26d9c3.js:69574:12
    jQuery 5
    start _application-4bbf4bf6518f7480549c54813a7fe09233841e43c49675ffe7fbda7ac187d247.js:8524
    forEach self-hosted:235
    start _application-4bbf4bf6518f7480549c54813a7fe09233841e43c49675ffe7fbda7ac187d247.js:8522
    <anonyme> _preload-application-data-c20deb0418fd87f5f03266570c4f93070c8325d5b49950d7621204a44b651901.js:28
    <anonyme> _preload-application-data-c20deb0418fd87f5f03266570c4f93070c8325d5b49950d7621204a44b651901.js:1
```

```
Error: Could not find module `@ember/runloop` imported from `discourse/plugins/discourse-calendar/widgets/discourse-group-timezones-slider` _ember_jquery-0ae86c6a7527a99c2b9b8a11521273bd9cb4f7d41bc546df081b7ee94f26d9c3.js:69574:12
    jQuery 5
    n _application-4bbf4bf6518f7480549c54813a7fe09233841e43c49675ffe7fbda7ac187d247.js:64053
    forEach self-hosted:235
    n _application-4bbf4bf6518f7480549c54813a7fe09233841e43c49675ffe7fbda7ac187d247.js:64048
    initialize _application-4bbf4bf6518f7480549c54813a7fe09233841e43c49675ffe7fbda7ac187d247.js:8532
    jQuery 21
```

And when I search for the 'rsvp' module in the discourse code, I get : https://github.com/discourse/discourse/search?q=rsvp&unscoped_q=rsvp

And I interpretated this as the need for ember.
And before tyring to install the other plugin (for Slack integration) I looked into the code, and it seems to need ember to.

**Comment by JimboJoe** [comment]
OK reproduced with that plugin (and not with the previous one).
I unfortunately don't have the knowledge to debug Discourse itself...
I advise you to try to reproduce your issue on a [Docker official installation](https://github.com/discourse/discourse/blob/master/docs/INSTALL-cloud.md) (with same stable version 2.3.10). If reproduced, you can then ask for help on the Discourse forum (the YunoHost "Docker-less" installation isn't supported there).

**Comment by Kapu06** [comment]
Ok, thank you :)
