### ISSUE TITLE
[buster] Install fails because dependency libjemalloc1 ain't available anymore, should be replaced by libjemalloc2 I believe

### ISSUE THREAD

**Issue by alexAubin** [YunoHost-Apps/discourse_ynh#56]
This dependency was added back to https://github.com/YunoHost-Apps/discourse_ynh/commit/5be413e2dd754c1b45531ecb89b5e1b037420cd5

Unfortunately this package ain't available for buster (c.f. [here](https://packages.debian.org/stretch/libjemalloc1), lack of 'buster' link in top right corner) but there's a similar one on buster which is called [libjemalloc2](https://packages.debian.org/buster/libjemalloc2) (but I have no idea what/why this dependency is needed by discourse so can't really say for sure, should look at the install instructions I guess)

Anyway, if this is the right solution, possibly just using the 'or' syntax to require either of package should be the appropriate fix I suppose.

**Comment by JimboJoe** [comment]
Thanks for the report!
FYI, jemalloc is said to improve drastically Ruby memory management.
I'll have a look when I find time to set up an additional Buster environment.

**Comment by maniackcrudelis** [comment]
`checkinstall` is also missing on Buster...
