### ISSUE TITLE
Upgrade Discourse to 2.4.2

### ISSUE THREAD

**Issue by Murloc6** [YunoHost-Apps/discourse_ynh#58]
We tried to install the plugin chat-integration to set up a discourse/matrix bridge. This plugin uses some features included since the v2.4.2 of Discourse.
We find a workaround in using a previous version of the plugin. But we would appreciate upgrading Discourse directly from Yunohost. Is there any project to do so?

Thank you for your work, we use this instance daily and this is amazing.

cc @arthurlogilab

**Comment by JimboJoe** [comment]
Please see #33 
Long story short: requires redis 4.0, hence YunoHost 4.0 (Buster port). So definitely planned, but please don't hold your breathe :slightly_smiling_face:
