### ISSUE TITLE
Symbols and Menu items missing

### ISSUE THREAD

**Issue by hermann-san** [YunoHost-Apps/discourse_ynh#60]
After successful installation (well I can access the forum) of the latest yunohost with the latest available Discourse Forum, I get the following issues. All the yellow marked symbols in the below screenshots (like's, edits buttons etc.) and menu-items are missing in my discourse forum. This issue is also there in the admin setting and other places.
There are [quite a few installation errors](https://hastebin.com/ipatuyitem.cs)  like the following.  For the full log, click on the aformentioned link

> precompile target: admin
> fatal: Not a git repository (or any of the parent directories): .git

> pngquant worker: `pngquant` not found; please provide proper binary or disable this worker (--no-pngquant argument or `:pngquant => false` through options)
> 
-------------------------------

> tail: cannot open '/var/www/discourse/log/unicorn.stderr.log' for reading: No such file or directory
> 
> Starting of discourse
> 
> /!\ Packagers! This app is still using the skipped/protected/unprotected_uris/regex settings which are now obsolete and deprecated... Instead, you should use the new helpers 'ynh_permission_{create,urls,update,delete}' and the 'visitors' group to initialize the public/private access. Check out the documentation at the bottom of yunohost.org/groups_and_permissions to learn how to use the new permission mechanism.

> Created symlink /etc/systemd/system/multi-user.target.wants/discourse.service → /etc/systemd/system/discourse.service.
> 
> stty: 'standard input': Inappropriate ioctl for device
> 
> stty: 'standard input': Inappropriate ioctl for device
> 
> stty: 'standard input': Inappropriate ioctl for device
> 
> stty: 'standard input': Inappropriate ioctl for device
> 
> stty: 'standard input': Inappropriate ioctl for device
> 
> stty: 'standard input': Inappropriate ioctl for device
> 
> fatal: Not a git repository (or any of the parent directories): .git
> 
> fatal: Not a git repository (or any of the parent directories): .git
> 
> Done compiling CSS: 2020-07-18 11:32:18 UTC
> 

I've already tried re-installing discourse and tried with 5 different browser.
Any idea why this is and how to fix it?
Thanks in advance for any hints or comments.

----------------------------------------------
### **This is how it should be**
----------------------------------------------

![Auswahl_014](https://user-images.githubusercontent.com/7679654/87852038-eeb04800-c8fe-11ea-83cf-fc423bd67301.png)

--------------------------------------------
### **Below is how it actually is.  Notice that all of the yellow items above are missing**
----------------------------------------------

![Auswahl_015](https://user-images.githubusercontent.com/7679654/87852054-10113400-c8ff-11ea-9803-b2a4fd90bf2b.png)

****

**Comment by yalh76** [comment]
Can you try with the last version, now pngquant is included

**Comment by hermann-san** [comment]
it now works. thanks.
