### ISSUE TITLE
Upgrading to 2.6.0 fails and removes application

### ISSUE THREAD

**Issue by arthurzenika** [YunoHost-Apps/discourse_ynh#68]
**Describe the bug**

Upgrading to 2.6.0 fails and removes application

**Versions**
- Hardware: *amd64 VM.*
- YunoHost version: 4.1.4
- I have access to my server: *Through SSH | through the webadmin*
- Are you in a special context or did you perform some particular tweaking on your YunoHost instance ?: *no*
- If upgrading, current package version: from 2.3.10 to 2.6.0 (2.3.10 found in etckeeper version of `yunohost/apps/discourse/conf/app.src `)

**To Reproduce**
Once I've filed this issue, I'll try to restore backup and tell you if can reproduce. 

**Expected behavior**

Fail is OK as long as it rolls back to working version. 

**Logs**
https://paste.yunohost.org/raw/ogawuwizor
https://paste.yunohost.org/raw/fuwodefake

**Comment by miloskroulik** [comment]
I just would like to mention the problem is related to the `solved` plugin. And looking at https://meta.discourse.org/t/discourse-solved-accepted-answer-plugin/30155 it looks like it's an issue with this package.

**Comment by arthurlogilab** [comment]
Good catch, that plugin was added manually (sorry for the absence of mention in the "special context" question, I totally forgot about it). Restore worked, I'll look into making sure the plugin is up-gradable. Do you think there is way to avoid the deletion of the app in this case ? Is it a yunohost core bug ?
