### ISSUE TITLE
Install not posib.. 3.3.1 please help

### ISSUE THREAD

**Issue by wivodaimcom** [YunoHost-Apps/discourse_ynh#7]
32425 DEBUG Exécution de la commande « sh -c YNH_APP_INSTANCE_NUMBER=1 YNH_CWD=/var/cache/yunohost/from_file/discourse_ynh-master/scripts YNH_APP_ARG_IS_PUBLIC=1 YNH_STDINFO=/tmp/tmpKzq_lu/stdinfo YNH_APP_INSTANCE_NAME=discourse YNH_APP_ARG_ADMIN=wivodaim YNH_APP_ID=discourse YNH_APP_ARG_PATH=/ YNH_APP_ARG_DOMAIN=forum.wivodaim.com BASH_XTRACEFD=7 /bin/bash -x "./install" forum.wivodaim.com / wivodaim 1 discourse 7>&1 »...
32426 DEBUG About to run the command '['sh', '-c', 'YNH_APP_INSTANCE_NUMBER=1 YNH_CWD=/var/cache/yunohost/from_file/discourse_ynh-master/scripts YNH_APP_ARG_IS_PUBLIC=1 YNH_STDINFO=/tmp/tmpKzq_lu/stdinfo YNH_APP_INSTANCE_NAME=discourse YNH_APP_ARG_ADMIN=wivodaim YNH_APP_ID=discourse YNH_APP_ARG_PATH=/ YNH_APP_ARG_DOMAIN=forum.wivodaim.com BASH_XTRACEFD=7 /bin/bash -x "./install" forum.wivodaim.com / wivodaim 1 discourse 7>&1']'
32478 DEBUG + shopt -s extglob
32479 WARNING This path already contains a folder
32479 DEBUG + source /usr/share/yunohost/helpers
32480 WARNING !!
32480 DEBUG +++ run-parts --list /usr/share/yunohost/helpers.d
32480 WARNING   discourse's script has encountered an error. Its execution was cancelled.
32480 DEBUG ++ for helper in $(run-parts --list /usr/share/yunohost/helpers.d 2>/dev/null)
32481 WARNING !!
32481 DEBUG ++ '[' -r /usr/share/yunohost/helpers.d/backend ']'
32481 WARNING 
32482 DEBUG ++ . /usr/share/yunohost/helpers.d/backend
32482 DEBUG ++ for helper in $(run-parts --list /usr/share/yunohost/helpers.d 2>/dev/null)
32482 DEBUG ++ '[' -r /usr/share/yunohost/helpers.d/filesystem ']'
32483 DEBUG ++ . /usr/share/yunohost/helpers.d/filesystem
32483 DEBUG +++ CAN_BIND=1
32483 DEBUG ++ for helper in $(run-parts --list /usr/share/yunohost/helpers.d 2>/dev/null)
32483 DEBUG ++ '[' -r /usr/share/yunohost/helpers.d/getopts ']'
32484 DEBUG ++ . /usr/share/yunohost/helpers.d/getopts
32484 DEBUG ++ for helper in $(run-parts --list /usr/share/yunohost/helpers.d 2>/dev/null)
32485 DEBUG ++ '[' -r /usr/share/yunohost/helpers.d/ip ']'
32485 DEBUG ++ . /usr/share/yunohost/helpers.d/ip
32485 DEBUG ++ for helper in $(run-parts --list /usr/share/yunohost/helpers.d 2>/dev/null)
32486 DEBUG ++ '[' -r /usr/share/yunohost/helpers.d/mysql ']'
32486 DEBUG ++ . /usr/share/yunohost/helpers.d/mysql
32486 DEBUG +++ MYSQL_ROOT_PWD_FILE=/etc/yunohost/mysql
32486 DEBUG ++ for helper in $(run-parts --list /usr/share/yunohost/helpers.d 2>/dev/null)
32487 DEBUG ++ '[' -r /usr/share/yunohost/helpers.d/network ']'
32487 DEBUG ++ . /usr/share/yunohost/helpers.d/network
32487 DEBUG ++ for helper in $(run-parts --list /usr/share/yunohost/helpers.d 2>/dev/null)
32488 DEBUG ++ '[' -r /usr/share/yunohost/helpers.d/nodejs ']'
32488 DEBUG ++ . /usr/share/yunohost/helpers.d/nodejs
32488 DEBUG +++ n_install_dir=/opt/node_n
32489 DEBUG +++ node_version_path=/opt/node_n/n/versions/node
32489 DEBUG +++ export N_PREFIX=/opt/node_n
32489 DEBUG +++ N_PREFIX=/opt/node_n
32489 DEBUG ++ for helper in $(run-parts --list /usr/share/yunohost/helpers.d 2>/dev/null)
32490 DEBUG ++ '[' -r /usr/share/yunohost/helpers.d/package ']'
32491 DEBUG ++ . /usr/share/yunohost/helpers.d/package
32491 DEBUG ++ for helper in $(run-parts --list /usr/share/yunohost/helpers.d 2>/dev/null)
32492 DEBUG ++ '[' -r /usr/share/yunohost/helpers.d/print ']'
32492 DEBUG ++ . /usr/share/yunohost/helpers.d/print
32492 DEBUG ++ for helper in $(run-parts --list /usr/share/yunohost/helpers.d 2>/dev/null)
32493 DEBUG ++ '[' -r /usr/share/yunohost/helpers.d/psql ']'
32493 DEBUG ++ . /usr/share/yunohost/helpers.d/psql
32493 DEBUG ++ for helper in $(run-parts --list /usr/share/yunohost/helpers.d 2>/dev/null)
32495 DEBUG ++ '[' -r /usr/share/yunohost/helpers.d/setting ']'
32496 DEBUG ++ . /usr/share/yunohost/helpers.d/setting
32496 DEBUG ++ for helper in $(run-parts --list /usr/share/yunohost/helpers.d 2>/dev/null)
32496 DEBUG ++ '[' -r /usr/share/yunohost/helpers.d/string ']'
32497 DEBUG ++ . /usr/share/yunohost/helpers.d/string
32497 DEBUG ++ for helper in $(run-parts --list /usr/share/yunohost/helpers.d 2>/dev/null)
32497 DEBUG ++ '[' -r /usr/share/yunohost/helpers.d/system ']'
32498 DEBUG ++ . /usr/share/yunohost/helpers.d/system
32498 DEBUG ++ for helper in $(run-parts --list /usr/share/yunohost/helpers.d 2>/dev/null)
32498 DEBUG ++ '[' -r /usr/share/yunohost/helpers.d/user ']'
32499 DEBUG ++ . /usr/share/yunohost/helpers.d/user
32499 DEBUG ++ for helper in $(run-parts --list /usr/share/yunohost/helpers.d 2>/dev/null)
32500 DEBUG ++ '[' -r /usr/share/yunohost/helpers.d/utils ']'
32500 DEBUG ++ . /usr/share/yunohost/helpers.d/utils
32500 DEBUG + source _common.sh
32501 DEBUG ++ pkg_dependencies='libjemalloc1 libjemalloc-dev zlib1g-dev libreadline-dev libpq-dev libssl-dev libyaml-dev libcurl4-openssl-dev libapr1-dev libxslt1-dev checkinstall libxml2-dev vim imagemagick postgresql postgresql-server-dev-all postgresql-contrib optipng jhead jpegoptim gifsicle'
32501 DEBUG ++ RUBY_VERSION=2.4.4
32501 DEBUG ++ rbenv_install_dir=/opt/rbenv
32501 DEBUG ++ export RBENV_ROOT=/opt/rbenv
32502 DEBUG ++ RBENV_ROOT=/opt/rbenv
32502 DEBUG + ynh_abort_if_errors
32502 DEBUG + set -eu
32502 DEBUG + trap ynh_exit_properly EXIT
32503 DEBUG + app=discourse
32503 DEBUG + domain=forum.wivodaim.com
32503 DEBUG + path_url=/
32503 DEBUG + admin=wivodaim
32504 DEBUG + is_public=1
32504 DEBUG ++ ynh_normalize_url_path /
32504 DEBUG ++ local path_url=/
32504 DEBUG ++ test -n /
32505 DEBUG ++ '[' / '!=' / ']'
32505 DEBUG ++ '[' / == / ']'
32505 DEBUG ++ '[' 1 -gt 1 ']'
32505 DEBUG ++ echo /
32506 DEBUG + path_url=/
32506 DEBUG + final_path=/var/www/discourse
32506 DEBUG + test '!' -e /var/www/discourse
32507 DEBUG + ynh_die 'This path already contains a folder'
32507 DEBUG + echo 'This path already contains a folder'
32507 DEBUG + exit 1
32507 DEBUG + ynh_exit_properly
32508 DEBUG + local exit_code=1
32508 DEBUG + '[' 1 -eq 0 ']'
32508 DEBUG + trap '' EXIT
32508 DEBUG + set +eu
32509 DEBUG + echo -e '!!\n  discourse'\''s script has encountered an error. Its execution was cancelled.\n!!'
32509 DEBUG + type -t ynh_clean_setup
32509 DEBUG + ynh_clean_setup
32509 DEBUG + ynh_clean_check_starting
32510 DEBUG + kill -s 15
32510 DEBUG kill : utilisation :kill [-s sigspec | -n signum | -sigspec] pid | jobspec ... ou kill -l [sigspec]
32510 DEBUG + ynh_secure_remove ''
32511 DEBUG + local path_to_remove=
32511 DEBUG + local 'forbidden_path=    /var/www        /home/yunohost.app'
32511 DEBUG + [[        /var/www        /home/yunohost.app =~ '' ]]
32511 DEBUG + echo 'Avoid deleting .'
32512 DEBUG Avoid deleting .
32512 DEBUG + ynh_die
32512 DEBUG + echo ''
32513 DEBUG + exit 1
32650 INFO L’opération « Installer l’application « discourse » » a échouée ! Pour avoir de l’aide, merci de partager le log de cette opération en utilisant la commande « yunohost log display 20181201-124842-app_install-discourse --share »
32678 DEBUG Exécution de la commande « sh -c YNH_APP_INSTANCE_NUMBER=1 YNH_APP_ID=discourse YNH_CWD=/var/cache/yunohost/from_file/discourse_ynh-master/scripts YNH_APP_INSTANCE_NAME=discourse YNH_STDINFO=/tmp/tmpqLUlIQ/stdinfo BASH_XTRACEFD=7 /bin/bash -x "./remove" discourse 7>&1 »...
32679 DEBUG About to run the command '['sh', '-c', 'YNH_APP_INSTANCE_NUMBER=1 YNH_APP_ID=discourse YNH_CWD=/var/cache/yunohost/from_file/discourse_ynh-master/scripts YNH_APP_INSTANCE_NAME=discourse YNH_STDINFO=/tmp/tmpqLUlIQ/stdinfo BASH_XTRACEFD=7 /bin/bash -x "./remove" discourse 7>&1']'
32721 DEBUG + source /usr/share/yunohost/helpers
32725 DEBUG +++ run-parts --list /usr/share/yunohost/helpers.d
32826 DEBUG ++ for helper in $(run-parts --list /usr/share/yunohost/helpers.d 2>/dev/null)
32827 DEBUG ++ '[' -r /usr/share/yunohost/helpers.d/backend ']'
32827 DEBUG ++ . /usr/share/yunohost/helpers.d/backend
32827 DEBUG ++ for helper in $(run-parts --list /usr/share/yunohost/helpers.d 2>/dev/null)
32828 DEBUG ++ '[' -r /usr/share/yunohost/helpers.d/filesystem ']'
32828 DEBUG ++ . /usr/share/yunohost/helpers.d/filesystem
32828 DEBUG +++ CAN_BIND=1
32828 DEBUG ++ for helper in $(run-parts --list /usr/share/yunohost/helpers.d 2>/dev/null)
32829 DEBUG ++ '[' -r /usr/share/yunohost/helpers.d/getopts ']'
32829 DEBUG ++ . /usr/share/yunohost/helpers.d/getopts
32829 DEBUG ++ for helper in $(run-parts --list /usr/share/yunohost/helpers.d 2>/dev/null)
32830 DEBUG ++ '[' -r /usr/share/yunohost/helpers.d/ip ']'
32830 DEBUG ++ . /usr/share/yunohost/helpers.d/ip
32830 DEBUG ++ for helper in $(run-parts --list /usr/share/yunohost/helpers.d 2>/dev/null)
32831 DEBUG ++ '[' -r /usr/share/yunohost/helpers.d/mysql ']'
32831 DEBUG ++ . /usr/share/yunohost/helpers.d/mysql
32831 DEBUG +++ MYSQL_ROOT_PWD_FILE=/etc/yunohost/mysql
32832 DEBUG ++ for helper in $(run-parts --list /usr/share/yunohost/helpers.d 2>/dev/null)
32832 DEBUG ++ '[' -r /usr/share/yunohost/helpers.d/network ']'
32832 DEBUG ++ . /usr/share/yunohost/helpers.d/network
32833 DEBUG ++ for helper in $(run-parts --list /usr/share/yunohost/helpers.d 2>/dev/null)
32846 DEBUG ++ '[' -r /usr/share/yunohost/helpers.d/nodejs ']'
32846 DEBUG ++ . /usr/share/yunohost/helpers.d/nodejs
32847 DEBUG +++ n_install_dir=/opt/node_n
32847 DEBUG +++ node_version_path=/opt/node_n/n/versions/node
32847 DEBUG +++ export N_PREFIX=/opt/node_n
32848 DEBUG +++ N_PREFIX=/opt/node_n
32848 DEBUG ++ for helper in $(run-parts --list /usr/share/yunohost/helpers.d 2>/dev/null)
32849 DEBUG ++ '[' -r /usr/share/yunohost/helpers.d/package ']'
32851 DEBUG ++ . /usr/share/yunohost/helpers.d/package
32851 DEBUG ++ for helper in $(run-parts --list /usr/share/yunohost/helpers.d 2>/dev/null)
32851 DEBUG ++ '[' -r /usr/share/yunohost/helpers.d/print ']'
32852 DEBUG ++ . /usr/share/yunohost/helpers.d/print
32854 DEBUG ++ for helper in $(run-parts --list /usr/share/yunohost/helpers.d 2>/dev/null)
32859 DEBUG ++ '[' -r /usr/share/yunohost/helpers.d/psql ']'
32859 DEBUG ++ . /usr/share/yunohost/helpers.d/psql
32875 DEBUG ++ for helper in $(run-parts --list /usr/share/yunohost/helpers.d 2>/dev/null)
32875 DEBUG ++ '[' -r /usr/share/yunohost/helpers.d/setting ']'
32879 DEBUG ++ . /usr/share/yunohost/helpers.d/setting
32886 DEBUG ++ for helper in $(run-parts --list /usr/share/yunohost/helpers.d 2>/dev/null)
32887 DEBUG ++ '[' -r /usr/share/yunohost/helpers.d/string ']'
32887 DEBUG ++ . /usr/share/yunohost/helpers.d/string
32887 DEBUG ++ for helper in $(run-parts --list /usr/share/yunohost/helpers.d 2>/dev/null)
32888 DEBUG ++ '[' -r /usr/share/yunohost/helpers.d/system ']'
32888 DEBUG ++ . /usr/share/yunohost/helpers.d/system
32888 DEBUG ++ for helper in $(run-parts --list /usr/share/yunohost/helpers.d 2>/dev/null)
32895 DEBUG ++ '[' -r /usr/share/yunohost/helpers.d/user ']'
32895 DEBUG ++ . /usr/share/yunohost/helpers.d/user
32895 DEBUG ++ for helper in $(run-parts --list /usr/share/yunohost/helpers.d 2>/dev/null)
32896 DEBUG ++ '[' -r /usr/share/yunohost/helpers.d/utils ']'
32896 DEBUG ++ . /usr/share/yunohost/helpers.d/utils
32896 DEBUG + source _common.sh
32897 DEBUG ++ pkg_dependencies='libjemalloc1 libjemalloc-dev zlib1g-dev libreadline-dev libpq-dev libssl-dev libyaml-dev libcurl4-openssl-dev libapr1-dev libxslt1-dev checkinstall libxml2-dev vim imagemagick postgresql postgresql-server-dev-all postgresql-contrib optipng jhead jpegoptim gifsicle'
32897 DEBUG ++ RUBY_VERSION=2.4.4
32897 DEBUG ++ rbenv_install_dir=/opt/rbenv
32898 DEBUG ++ export RBENV_ROOT=/opt/rbenv
32898 DEBUG ++ RBENV_ROOT=/opt/rbenv
32898 DEBUG + app=discourse
32902 DEBUG ++ ynh_app_setting_get discourse domain
32903 DEBUG ++ sudo yunohost app setting discourse domain --output-as plain --quiet
33404 DEBUG + domain=
33405 DEBUG ++ ynh_app_setting_get discourse db_name
33405 DEBUG ++ sudo yunohost app setting discourse db_name --output-as plain --quiet
33906 DEBUG + db_name=
33907 DEBUG ++ ynh_app_setting_get discourse final_path
33907 DEBUG ++ sudo yunohost app setting discourse final_path --output-as plain --quiet
34409 DEBUG + final_path=
34409 DEBUG ++ ynh_app_setting_get discourse redis_db
34409 DEBUG ++ sudo yunohost app setting discourse redis_db --output-as plain --quiet
34911 DEBUG + redis_db=
34912 DEBUG + ynh_remove_systemd_config
34912 DEBUG + local service_name=discourse
34913 DEBUG + local finalsystemdconf=/etc/systemd/system/discourse.service
34913 DEBUG + '[' -e /etc/systemd/system/discourse.service ']'
34914 DEBUG + grep -q discourse
34914 DEBUG + yunohost service status
35817 DEBUG + ynh_remove_app_dependencies
35817 DEBUG + local dep_app=discourse
35818 DEBUG + ynh_package_autopurge discourse-ynh-deps
35818 DEBUG + ynh_apt autoremove --purge discourse-ynh-deps
35819 DEBUG + ynh_wait_dpkg_free
35819 DEBUG + local try
35820 DEBUG ++ seq 1 17
35821 DEBUG + for try in `seq 1 17`
35821 DEBUG + sudo lsof /var/lib/dpkg/lock
35922 WARNING lsof: WARNING: can't stat() fuse.gvfsd-fuse file system /run/user/1000/gvfs
35923 WARNING       Output information may be incomplete.
36525 DEBUG + break
36525 DEBUG + echo 'apt still used, but timeout reached !'
36525 DEBUG apt still used, but timeout reached !
36525 DEBUG + DEBIAN_FRONTEND=noninteractive
36526 DEBUG + sudo apt-get -y autoremove --purge discourse-ynh-deps
36726 DEBUG Lecture des listes de paquets…
37329 DEBUG Construction de l'arbre des dépendances…
37331 DEBUG Lecture des informations d'état…
37433 DEBUG + ynh_remove_ruby
37434 WARNING E: Impossible de trouver le paquet discourse-ynh-deps
37435 DEBUG ++ ynh_app_setting_get discourse ruby_version
37435 DEBUG ++ sudo yunohost app setting discourse ruby_version --output-as plain --quiet
38037 DEBUG + ruby_version=
38038 WARNING sed: impossible de lire /opt/rbenv/ynh_app_version: Aucun fichier ou dossier de ce type
38038 DEBUG + sed --in-place /discourse:/d /opt/rbenv/ynh_app_version
38039 WARNING grep: /opt/rbenv/ynh_app_version: Aucun fichier ou dossier de ce type
38040 DEBUG + grep --quiet '' /opt/rbenv/ynh_app_version
38040 WARNING _common.sh: ligne 444: /opt/rbenv/bin/rbenv: Aucun fichier ou dossier de ce type
38041 DEBUG + /opt/rbenv/bin/rbenv uninstall --force
38042 WARNING rm: impossible de supprimer '/etc/profile.d/rbenv.sh': Aucun fichier ou dossier de ce type
38042 DEBUG + rm /etc/profile.d/rbenv.sh
38043 WARNING /opt/rbenv wasn't deleted because it doesn't exist.
38043 DEBUG + '[' '!' -s /opt/rbenv/ynh_app_version ']'
38044 DEBUG + ynh_secure_remove /opt/rbenv
38045 DEBUG + local path_to_remove=/opt/rbenv
38045 DEBUG + local 'forbidden_path=    /var/www        /home/yunohost.app'
38046 DEBUG + [[        /var/www        /home/yunohost.app =~ /opt/rbenv ]]
38047 DEBUG + [[ /opt/rbenv =~ ^/[[:alnum:]]+$ ]]
38047 DEBUG + [[ v = \/ ]]
38048 DEBUG + '[' -e /opt/rbenv ']'
38049 DEBUG + echo '/opt/rbenv wasn'\''t deleted because it doesn'\''t exist.'
38049 DEBUG + ynh_psql_remove_db
38050 DEBUG + db=
38051 DEBUG + user=
38052 DEBUG + sudo --login --user=postgres dropdb ''
38153 DEBUG + ynh_psql_drop_user ''
38153 WARNING dropdb : argument nom de la base de données requis mais manquant
38154 DEBUG + user=
38154 WARNING Essayer « dropdb --help » pour plus d'informations.
38154 DEBUG + sudo --login --user=postgres dropuser ''
38355 DEBUG + ynh_redis_remove_db ''
38356 WARNING dropuser : argument nom du rôle requis mais manquant
38356 DEBUG + local db=
38357 WARNING Essayer « dropuser --help » pour plus d'informations.
38357 DEBUG + redis-cli -n '' flushall
38462 DEBUG OK
38463 WARNING Avoid deleting .
38463 DEBUG + ynh_secure_remove ''
38464 WARNING /etc/nginx/conf.d/.d/discourse.conf wasn't deleted because it doesn't exist.
38464 DEBUG + local path_to_remove=
38464 DEBUG + local 'forbidden_path=    /var/www        /home/yunohost.app'
38464 DEBUG + [[        /var/www        /home/yunohost.app =~ '' ]]
38465 DEBUG + echo 'Avoid deleting .'
38465 DEBUG + ynh_remove_nginx_config
38465 DEBUG + ynh_secure_remove /etc/nginx/conf.d/.d/discourse.conf
38466 DEBUG + local path_to_remove=/etc/nginx/conf.d/.d/discourse.conf
38466 DEBUG + local 'forbidden_path=    /var/www        /home/yunohost.app'
38466 DEBUG + [[        /var/www        /home/yunohost.app =~ /etc/nginx/conf\.d/\.d/discourse\.conf ]]
38471 DEBUG + [[ /etc/nginx/conf.d/.d/discourse.conf =~ ^/[[:alnum:]]+$ ]]
38471 DEBUG + [[ f = \/ ]]
38471 DEBUG + '[' -e /etc/nginx/conf.d/.d/discourse.conf ']'
38472 DEBUG + echo '/etc/nginx/conf.d/.d/discourse.conf wasn'\''t deleted because it doesn'\''t exist.'
38472 DEBUG + sudo systemctl reload nginx
38773 DEBUG + ynh_remove_logrotate
38774 WARNING The user discourse was not found
38774 DEBUG + '[' -e /etc/logrotate.d/discourse ']'
38774 DEBUG + ynh_system_user_delete discourse
38774 DEBUG + ynh_system_user_exists discourse
38775 DEBUG + getent passwd discourse
38775 DEBUG + echo 'The user discourse was not found'
38915 DEBUG Pour voir le log de cette opération « Enlever « discourse » après une installation échouée », utiliser la commande « yunohost log display 20181201-124843-remove_on_failed_install-discourse »
41406 SUCCESS La configuration de SSOwat a été générée
41406 DEBUG action [2943.1] executed in 40.893s
41407 DEBUG lock has been released
41407 ERROR L’opération « Installer l’application « discourse » » a échouée ! Pour avoir de l’aide, merci de partager le log de cette opération en utilisant la commande « yunohost log display 20181201-124842-app_install-discourse --share »

**Comment by Josue-T** [comment]
Did you try to install discourse an other time ?

I look like the folder `/var/www/discourse` is already used.

I think you could remove this folder if it's not used by anything else and if there are no important information.

**Comment by JimboJoe** [comment]
Was your issue closed by removing the ̀/var/www/discourse` directory?

**Comment by JimboJoe** [comment]
I'm closing this issue; don't hesitate to re-open it if needed :wink:
