### ISSUE TITLE
yunohost integration Level 0 

### ISSUE THREAD

**Issue by Schoebi** [YunoHost-Apps/discourse_ynh#73]
Since my last installation on a yunohost server the integration Level fell from 7 to 0.

Yunohost sais it's unsafe to install. 

Will the integration level rise again?

What is the danger if I install it?

And: Is this the right place to ask this questions? (on the yunohost forum I didn't get an answer)

**Comment by ericgaspar** [comment]
Discourse level was set to 0 due to the CI not handling swap. This should be fixed now.
