### ISSUE TITLE
I try update from 2.6.1 to 2.7.4 but...

### ISSUE THREAD

**Issue by dislive** [YunoHost-Apps/discourse_ynh#81]
my yunohost 4.2.6.1 (stable)
I try update from 2.6.1 to 2.7.4

` sudo yunohost app upgrade discourse -u https://github.com/YunoHost-Apps/discourse_ynh/tree/testing`
and got error
`Requirements are not met for discourse, the package yunohost (0:) must be >= 4.1.7`

_Originally posted by @dislive in https://github.com/YunoHost-Apps/discourse_ynh/issues/76#issuecomment-872472696_

**Comment by ericgaspar** [comment]
Are you able to update to version 2.7.6 now on the main branch?

**Comment by dislive** [comment]
> Are you able to update to version 2.7.6 now on the main branch?

Has been successfully updated to the latest version. Thanks to!
